### PR TITLE
 App strings reworked

### PR DESCRIPTION
**Pull request by comradekingu**
Somehow the this is missing here, but included in F-Droid build…

"ARIA HINT - This is the now playing episode in a carousel": "This is the now playing episode...swipe to the right to view different information...tap on the bottom of the screen for the player controls",
 (my take)
"ARIA HINT - This is the now playing episode in a carousel": "The currently playing episode…swipe rightwards to view different info…tap the bottom of the screen for player controls",

---
Original PR https://github.com/podverse/podverse-fdroid/pull/52/files for the F-Droid build, because I dumbed.

### CODE REVIEW

**Comment by mitchdowney** [comment]
@comradekingu are you signed up for Hacktoberfest? If you make 4 open source contributions in a month (to Github repos that have the `hacktoberfest` topic on it), then you'll get a free t-shirt. Digital Ocean runs it every year and the shirts are usually pretty cool.

**Comment by comradekingu** [comment]
@mitchdowney 
I haven't done hacktoberfest, but I appreciate the effort.
A lot less spam this year, so that is good.

**Comment by mitchdowney** [comment]
Awesome @comradekingu thanks again for your help :)

We might adjust the language in a few of these, but overall they're a big improvement over the previous text.

**Comment by comradekingu** [comment]
@mitchdowney That is a great way to do things.
Do tag me so I can keep track of what consistency exists.
If you add https://hosted.weblate.org/user/kingu/ to https://hosted.weblate.org/projects/podverse-mobile-app/
I can try to set it up for translation :)

**Pull request merged**
