### PR TITLE
fix: android auto content grid style

### LINKED ISSUE #1977: Android Auto episode changes between list and grid view
**Describe the bug**
I have my Podverse app set to use the Grid View. I've noticed that if Podvers isn't already running and Android Auto launches it, the episodes are shown in a List View. If Podverse is already running and Android Auto is connected, it seems to follow my setting of Grid View.

**To Reproduce**
1. Configure episode page for grid view
2. Connect phone to Android Auto
3. Open Podverse on the head unit
4. Notice the episodes are shown in a Grid View
5. Disconnect the phone from Android auto
6. Close the Podverse app on the phone (open recents and swipe it away)
7. Connect phone to Android Auto
8. Open Podverse on the head unit
9. Notice the episodes are shown in List View

**Expected behavior**
I don't care what view is used in Android Auto but I would expect the same view to be used regardless of open method.

**Screenshots**
Here are screenshots from the head unit showing the 2 different views.

grid_view
list_view

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S22 Ultra 5G
- OS: Android 13
- App Version: 4.14.0 Build 5218

### PR DESCRIPTION
**Pull request by lovegaoshi**
closes #1977 by force setting each podcast item's contentStyle to CategoryGrid.

### CODE REVIEW

**Comment by lovegaoshi** [comment]
unrelated, my ts plugin doesnt recognize RNTP's types anymore, unsure if it's because of 
`"react-native-track-player": "github:lovegaoshi/react-native-track-player#dev-podverse-aa",`

**Comment by lovegaoshi** [comment]
oops, I accidentally clicked push instead of creating a new branch:S well now this PR closes https://github.com/podverse/podverse-rn/issues/1758 too.

**Review by mitchdowney — APPROVED** [review]

**Comment by mitchdowney** [comment]
@lovegaoshi this looks good! Looks like we have to remember to update the yarn.lock file to make sure the package manager uses the latest branch version, not a cached version? If I understand that right I'll keep that in mind, thanks again.

**Comment by lovegaoshi** [comment]
I ported some changes in the custom RNTP podverse has hence the updated SHA; does podverse want to fork my RNTP fork so I dont accidentally push anything and create problems when rebuilding lockfiles?

**Comment by mitchdowney** [comment]
> does podverse want to fork my RNTP fork so I dont accidentally push anything and create problems when rebuilding lockfiles?

@lovegaoshi yeah, I should really do that. Adding it to my list for next release.

**Pull request merged**
