### PR TITLE
Feature/badwords

### PR DESCRIPTION
**Pull request by mitchdowney**

### CODE REVIEW

**Comment by mitchdowney** [comment]
The badwords feature is up. Instead of removing the episodes/clips that have profanity I am just censoring it. Decided to do this for 2 reasons:

1. Zebra striping currently checks if the index of the item to render is odd to determine color. We would need to remove items from the response itself to make this work, but doing that introduces a problem with 2…
2. When we request getEpisodes or getMediaRefs, the response data contains an array with two fields, 1) the results list (limited to 20 at a time) and 2) the total count of results for the query (which can be in the thousands). We need 2) in order to determine when the infinite scroll feature has reached the end of all results for the query.

1 and 2 together seemed overly complex, so I thought censoring profanity would be easier and better than nothing.

**Comment by kreonjr** [comment]
I do like the idea of just censoring but I think we can make it a little simpler than having to do all this manipulations and checks in the different files. I we we can enhance the String Prototype with a nice function called something like "sanitize".

It can just use a simple find and replace if the NSFW setting is on. The only challenge would be to get the option of nsfw or not.

`
const badWords = ["shit", "damn" ]

String.prototype.sanitize = function () {
  if(nsfw) {
    const pattern = badWords.join("|")
    const replace = `${pattern}`;
    const re = new RegExp(replace,"gi");
    return this.replace(re, (sub) => "*".repeat(sub.length))
  }

  return this.toString()
}
`

This way you can call `item.title.sanitize()` anywhere you want this to be sanitized and it will do it automatically for you. So "I don't give a shit, damn it" becomes "I don't give a ****, **** it"

Thoughts?

**Comment by mitchdowney** [comment]
That works for me. I’d suggest we still use this bad-words library because it censors multiple languages apparently.

Where should we put the string prototype extender?

**Comment by kreonjr** [comment]
Yes, definitely use the library, looks very thorough. We already have a Strings.js extension for `linkifyHtml` in src/lib/extensions/String.ts. I think that the idea place for that

**Comment by mitchdowney** [comment]
@kreonjr updated with String prototype method

**Comment by mitchdowney** [comment]
@kreonjr updated with a new approach.

**Pull request merged**
